@url = http://localhost:5216

GET {{url}}/api/Professors
Accept: application/json

###

GET {{url}}/api/Professors/9
Accept: application/json

###

POST {{url}}/api/Professors
Content-Type: application/json

{
    "name": "jafar",
    "lastName": "hosseini",
    "email": "jafar@gmail.com",
    "city": "sari",
    "street": "rahband"
}